export default [
  { county: 'Los Angeles', city: 'Santa Monica', tax: 1 },
  { county: 'Los Angeles', city: 'Los Angeles', tax: 4.50 },
  { county: 'Los Angeles', city: 'Pomona', tax: 2.20 },
  { county: 'Los Angeles', city: 'Redondo Beach', tax: 2.20 },
  { county: 'Los Angeles', city: 'Culver City', tax: 4.50 },
  { county: 'Los Angeles', city: 'Arleta', tax: 4.50 },
  { county: 'Los Angeles', city: 'Athens', tax: 4.50 },
  { county: 'Los Angeles', city: 'Bel Air', tax: 4.50 },
  { county: 'Los Angeles', city: 'Bel Air Estates', tax: 4.50 },
  { county: 'Los Angeles', city: 'Beverly Glen', tax: 4.50 },
  { county: 'Los Angeles', city: 'Boyle Heights', tax: 4.50 },
  { county: 'Los Angeles', city: 'Brentwood', tax: 4.50 },
  { county: 'Los Angeles', city: 'Cahuenga Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'Calabasas', tax: 4.50 },
  { county: 'Los Angeles', city: 'Canoga Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'Carson', tax: 4.50 },
  { county: 'Los Angeles', city: 'Castellamare', tax: 4.50 },
  { county: 'Los Angeles', city: 'Century City', tax: 4.50 },
  { county: 'Los Angeles', city: 'Chatsworth', tax: 4.50 },
  { county: 'Los Angeles', city: 'Crenshaw Distract', tax: 4.50 },
  { county: 'Los Angeles', city: 'Eagle Rock', tax: 4.50 },
  { county: 'Los Angeles', city: 'East L.A.', tax: 4.50 },
  { county: 'Los Angeles', city: 'East San Pedro', tax: 4.50 },
  { county: 'Los Angeles', city: 'Echo Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'El Sereno', tax: 4.50 },
  { county: 'Los Angeles', city: 'Elysian Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'Encino', tax: 4.50 },
  { county: 'Los Angeles', city: 'Gardena(Figueroa-Vermont)', tax: 4.50 },
  { county: 'Los Angeles', city: 'Garvanza', tax: 4.50 },
  { county: 'Los Angeles', city: 'Glassell Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'Granada Hills', tax: 4.50 },
  { county: 'Los Angeles', city: 'Hancock Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'Hansen Heights', tax: 4.50 },
  { county: 'Los Angeles', city: 'Harbor City', tax: 4.50 },
  { county: 'Los Angeles', city: 'Hidden Hills', tax: 4.50 },
  { county: 'Los Angeles', city: 'Highland Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'Hollywood', tax: 4.50 },
  { county: 'Los Angeles', city: 'Hyde Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'Inglewood', tax: 4.50 },
  { county: 'Los Angeles', city: 'Korea Town', tax: 4.50 },
  { county: 'Los Angeles', city: 'Lakeside Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'Lakeview Terrace', tax: 4.50 },
  { county: 'Los Angeles', city: 'Larchmont District', tax: 4.50 },
  { county: 'Los Angeles', city: 'La Tijera', tax: 4.50 },
  { county: 'Los Angeles', city: 'Laurel Canyon', tax: 4.50 },
  { county: 'Los Angeles', city: 'Leimert Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'Lincoln Heights', tax: 4.50 },
  { county: 'Los Angeles', city: 'Los Feliz', tax: 4.50 },
  { county: 'Los Angeles', city: 'Marina Del Rey', tax: 4.50 },
  { county: 'Los Angeles', city: 'Mar Vista', tax: 4.50 },
  { county: 'Los Angeles', city: 'Mission Hills', tax: 4.50 },
  { county: 'Los Angeles', city: 'Montecito Heights', tax: 4.50 },
  { county: 'Los Angeles', city: 'Monterey Hills', tax: 4.50 },
  { county: 'Los Angeles', city: 'Mt. Olympus', tax: 4.50 },
  { county: 'Los Angeles', city: 'Mt. Washington', tax: 4.50 },
  { county: 'Los Angeles', city: 'North Hills', tax: 4.50 },
  { county: 'Los Angeles', city: 'North Hollywood', tax: 4.50 },
  { county: 'Los Angeles', city: 'Northridge', tax: 4.50 },
  { county: 'Los Angeles', city: 'Olive View', tax: 4.50 },
  { county: 'Los Angeles', city: 'Pacific Palisades', tax: 4.50 },
  { county: 'Los Angeles', city: 'Pacoima', tax: 4.50 },
  { county: 'Los Angeles', city: 'Palasades Highlands', tax: 4.50 },
  { county: 'Los Angeles', city: 'Palms', tax: 4.50 },
  { county: 'Los Angeles', city: 'Panorama City', tax: 4.50 },
  { county: 'Los Angeles', city: 'Playa Del Rey', tax: 4.50 },
  { county: 'Los Angeles', city: 'Porter Ranch', tax: 4.50 },
  { county: 'Los Angeles', city: 'Rancho Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'Reseda', tax: 4.50 },
  { county: 'Los Angeles', city: 'San Pedro', tax: 4.50 },
  { county: 'Los Angeles', city: 'San Fernando', tax: 4.50 },
  { county: 'Los Angeles', city: 'Sawtelle', tax: 4.50 },
  { county: 'Los Angeles', city: 'Sepulveda', tax: 4.50 },
  { county: 'Los Angeles', city: 'Sherman Oaks', tax: 4.50 },
  { county: 'Los Angeles', city: 'Silver Lake', tax: 4.50 },
  { county: 'Los Angeles', city: 'Studio City', tax: 4.50 },
  { county: 'Los Angeles', city: 'Sunland', tax: 4.50 },
  { county: 'Los Angeles', city: 'Sun Valley', tax: 4.50 },
  { county: 'Los Angeles', city: 'Sylmar', tax: 4.50 },
  { county: 'Los Angeles', city: 'Sylmar Square', tax: 4.50 },
  { county: 'Los Angeles', city: 'Tarzana', tax: 4.50 },
  { county: 'Los Angeles', city: 'Terminal Island', tax: 4.50 },
  { county: 'Los Angeles', city: 'Toluca Lake', tax: 4.50 },
  { county: 'Los Angeles', city: 'Topanga', tax: 4.50 },
  { county: 'Los Angeles', city: 'Torrance', tax: 4.50 },
  { county: 'Los Angeles', city: 'Tjunga', tax: 4.50 },
  { county: 'Los Angeles', city: 'Universal City', tax: 4.50 },
  { county: 'Los Angeles', city: 'Valley Plaza', tax: 4.50 },
  { county: 'Los Angeles', city: 'Valley Village', tax: 4.50 },
  { county: 'Los Angeles', city: 'Van Nuys', tax: 4.50 },
  { county: 'Los Angeles', city: 'Venice', tax: 4.50 },
  { county: 'Los Angeles', city: 'Vernon', tax: 4.50 },
  { county: 'Los Angeles', city: 'View Park', tax: 4.50 },
  { county: 'Los Angeles', city: 'Warner Center', tax: 4.50 },
  { county: 'Los Angeles', city: 'Watts', tax: 4.50 },
  { county: 'Los Angeles', city: 'Westchester', tax: 4.50 },
  { county: 'Los Angeles', city: 'West Hills', tax: 4.50 },
  { county: 'Los Angeles', city: 'West Hollywood', tax: 4.50 },
  { county: 'Los Angeles', city: 'Westlake', tax: 4.50 },
  { county: 'Los Angeles', city: 'West L.A.', tax: 4.50 },
  { county: 'Los Angeles', city: 'Westwood', tax: 4.50 },
  { county: 'Los Angeles', city: 'Wilmington', tax: 4.50 },
  { county: 'Los Angeles', city: 'Wilshire Distract', tax: 4.50 },
  { county: 'Los Angeles', city: 'Windsor Hills', tax: 4.50 },
  { county: 'Los Angeles', city: 'Winnetka', tax: 4.50 },
  { county: 'Los Angeles', city: 'Woodland Hills', tax: 4.50 },
  { county: 'Los Angeles', city: 'Malibu', tax: 1 },
  { county: 'Alameda', city: 'Alameda', tax: 12.00 },
  { county: 'Alameda', city: 'Albany', tax:  11.50 },
  { county: 'Alameda', city: 'Berkeley', tax: 15.00 },
  { county: 'Alameda', city: 'Emeryville', tax: 12.00 },
  { county: 'Alameda', city: 'Hayward', tax: 4.50 },
  { county: 'Alameda', city: 'Oakland', tax: 15.00 },
  { county: 'Alameda', city: 'Piedmont', tax: 13.00 },
  { county: 'Alameda', city: 'San Leandro', tax: 6.00 },
  { county: 'Contra Costa', city: 'Richmond', tax: 7.00 },
  { county: 'Marin', city: 'San Rafael', tax: 2.00 },
  { county: 'Riverside', city: 'Riverside City', tax: 1.10 },
  { county: 'Sacramento', city: 'Sacramento City', tax: 2.75 },
  { county: 'San Mateo', city: 'Hillsborough', tax: 0.30 },
  { county: 'San Mateo', city: 'San Mateo', tax: 5.00 },
  { county: 'Santa Clara', city: 'Mountain View', tax: 3.30 },
  { county: 'Santa Clara', city: 'Palo Alto', tax: 3.30 },
  { county: 'Santa Clara', city: 'San Jose', tax: 3.30 },
  { county: 'Solano', city: 'Santa Rosa', tax: 2.00 },
  { county: 'Solano', city: 'Petaluma', tax: 2.00 },
  { county: 'Yolo', city: 'Woodland', tax: 1.10 }
]
