export default [
  { name: 'Los Angeles', tax: 1.10 },
  { name: 'San Francisco', tax: 3 },
  { name: 'Alameda', tax: 1.10 },
  { name: 'Alpine', tax: 1.10 },
  { name: 'Amador', tax: 1.10 },
  { name: 'Butte', tax: 1.10 },
  { name: 'Calaveras', tax: 1.10 },
  { name: 'Colusa', tax: 1.10 },
  { name: 'Contra Costa', tax: 1.10 },
  { name: 'Del Norte', tax: 1.10 },
  { name: 'El Dorado', tax: 1.10 },
  { name: 'Fresno', tax: 1.10 },
  { name: 'Glenn', tax: 1.10 },
  { name: 'Humboldt', tax: 1.10 },
  { name: 'Imperial', tax: 1.10 },
  { name: 'Inyo', tax: 1.10 },
  { name: 'Kern', tax: 1.10 },
  { name: 'Kings', tax: 1.10 },
  { name: 'Lake', tax: 1.10 },
  { name: 'Lassen', tax: 1.10 },
  { name: 'Madera', tax: 1.10 },
  { name: 'Marin', tax: 1.10 },
  { name: 'Mariposa', tax: 1.10 },
  { name: 'Mendocino', tax: 1.10 },
  { name: 'Merced', tax: 1.10 },
  { name: 'Modoc', tax: 1.10 },
  { name: 'Mono', tax: 1.10 },
  { name: 'Monterey', tax: 1.10 },
  { name: 'Napa', tax: 1.10 },
  { name: 'Nevada', tax: 1.10 },
  { name: 'Orange', tax: 1.10 },
  { name: 'Placer', tax: 1.10 },
  { name: 'Plumas', tax: 1.10 },
  { name: 'Riverside', tax: 1.10 },
  { name: 'Sacramento', tax: 1.10 },
  { name: 'San Benito', tax: 1.10 },
  { name: 'San Bernardino', tax: 1.10 },
  { name: 'San Diego', tax: 1.10 },
  { name: 'San Francisco', tax: 1.10 },
  { name: 'San Joaquin', tax: 1.10 },
  { name: 'San Luis Obispo', tax: 1.10 },
  { name: 'San Mateo', tax: 1.10 },
  { name: 'Santa Barbara', tax: 1.10 },
  { name: 'Santa Clara', tax: 1.10 },
  { name: 'Santa Cruz', tax: 1.10 },
  { name: 'Shasta', tax: 1.10 },
  { name: 'Sierra', tax: 1.10 },
  { name: 'Siskiyou', tax: 1.10 },
  { name: 'Solano', tax: 1.10 },
  { name: 'Sonoma', tax: 1.10 },
  { name: 'Stanislaus', tax: 1.10 },
  { name: 'Sutter', tax: 1.10 },
  { name: 'Tehama', tax: 1.10 },
  { name: 'Trinity', tax: 1.10 },
  { name: 'Tulare', tax: 1.10 },
  { name: 'Tuolumne', tax: 1.10 },
  { name: 'Ventura', tax: 1.10 },
  { name: 'Yolo', tax: 1.10 },
  { name: 'Yuba', tax: 1.10 }
]
